/**
 * Rebuilds the homepage technology strip from the `simple-icons` package so the
 * brand marks stay authentic instead of being hand-copied path data. Run after
 * bumping simple-icons or editing the STACK list:
 *
 *   node scripts/build_tech_strip.mjs && npm run format
 *
 * Output is written between the TECH-STRIP markers in index.html.
 */
import { readFile, writeFile } from "node:fs/promises";
import * as simpleIcons from "simple-icons";

/* Microsoft withdrew its marks from simple-icons over trademark policy, and SQL
   is a language rather than a brand, so both carry original glyphs drawn on the
   same 24x24 grid instead of a reproduction of someone else's logo. */
const CUSTOM = {
    sql: {
        title: "SQL",
        hex: "7D5A15",
        path: "M12 1.5c-4.7 0-8.5 1.4-8.5 3.2v14.6c0 1.8 3.8 3.2 8.5 3.2s8.5-1.4 8.5-3.2V4.7c0-1.8-3.8-3.2-8.5-3.2zm0 1.6c4 0 6.9 1.1 6.9 1.6S16 6.3 12 6.3 5.1 5.2 5.1 4.7 8 3.1 12 3.1zM5.1 7.1c1.6.8 4.1 1.2 6.9 1.2s5.3-.4 6.9-1.2v3.4c0 .5-2.9 1.6-6.9 1.6s-6.9-1.1-6.9-1.6zm0 5.6c1.6.8 4.1 1.2 6.9 1.2s5.3-.4 6.9-1.2v3.4c0 .5-2.9 1.6-6.9 1.6s-6.9-1.1-6.9-1.6zm0 5.6c1.6.8 4.1 1.2 6.9 1.2s5.3-.4 6.9-1.2v1c0 .5-2.9 1.6-6.9 1.6s-6.9-1.1-6.9-1.6z",
    },
    powerbi: {
        title: "Power BI",
        hex: "C4A017",
        path: "M2.75 20.4h3.6V9.9h-3.6zm3.6 0h3.6V4.5h-3.6zm7.3 0h3.6V7.2h-3.6zm3.6 0h3.6V1.8h-3.6zM1 21.4h22v1.4H1z",
    },
};

/* Ordered as the site describes the work: interfaces, then services, then data,
   then modelling, then delivery. */
const STACK = [
    "html5",
    "css",
    "javascript",
    "typescript",
    "react",
    "nextdotjs",
    "nodedotjs",
    "python",
    "django",
    "flask",
    "fastapi",
    "sql",
    "pandas",
    "numpy",
    "powerbi",
    "scikitlearn",
    "tensorflow",
    "keras",
    "jupyter",
    "git",
    "github",
];

/* Marks that are near-black read as smudges next to the coloured ones, so they
   are nudged toward the page's ink rather than left at their brand hex. */
const INK_SUBSTITUTES = {
    nextdotjs: "0A0A0A",
    github: "0A0A0A",
    pandas: "1B0552",
    numpy: "0B3A4C",
    django: "0C4B2E",
};

const slugToExport = (slug) => `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;

const icons = STACK.map((slug) => {
    const icon = CUSTOM[slug] ?? simpleIcons[slugToExport(slug)];
    if (!icon) throw new Error(`No icon available for "${slug}"`);
    return { slug, title: icon.title, hex: INK_SUBSTITUTES[slug] ?? icon.hex, path: icon.path };
});

const indent = (depth) => " ".repeat(depth * 4);

const symbols = icons
    .map(
        ({ slug, hex, path }) =>
            `${indent(4)}<symbol id="tech-${slug}" viewBox="0 0 24 24">\n` +
            `${indent(5)}<path fill="#${hex}" d="${path}" />\n` +
            `${indent(4)}</symbol>`,
    )
    .join("\n");

const listItems = (depth) =>
    icons
        .map(
            ({ slug, title }) =>
                `${indent(depth)}<li class="tech-chip">\n` +
                `${indent(depth + 1)}<svg class="tech-chip-mark" aria-hidden="true" focusable="false">` +
                `<use href="#tech-${slug}" /></svg>\n` +
                `${indent(depth + 1)}<span class="tech-chip-label">${title}</span>\n` +
                `${indent(depth)}</li>`,
        )
        .join("\n");

const section = `${indent(3)}<section class="section-compact tech-strip" aria-labelledby="stack-heading">
${indent(4)}<svg class="tech-sprite" aria-hidden="true" focusable="false" width="0" height="0">
${symbols}
${indent(4)}</svg>
${indent(4)}<div class="container">
${indent(5)}<div class="section-header tech-strip-header">
${indent(6)}<div>
${indent(7)}<p class="eyebrow">Working stack</p>
${indent(7)}<h2 id="stack-heading">The tools behind the work.</h2>
${indent(6)}</div>
${indent(6)}<p>Every technology below is one I build with directly, across interfaces, services, data, and models.</p>
${indent(5)}</div>
${indent(4)}</div>
${indent(4)}<div class="tech-marquee">
${indent(5)}<div class="tech-track">
${indent(6)}<ul class="tech-list">
${listItems(7)}
${indent(6)}</ul>
${indent(6)}<ul class="tech-list" aria-hidden="true">
${listItems(7)}
${indent(6)}</ul>
${indent(5)}</div>
${indent(4)}</div>
${indent(3)}</section>`;

const START = `${indent(3)}<!-- TECH-STRIP:START (generated by scripts/build_tech_strip.mjs) -->`;
const END = `${indent(3)}<!-- TECH-STRIP:END -->`;

const file = "index.html";
const html = await readFile(file, "utf8");
const startIndex = html.indexOf(START);
const endIndex = html.indexOf(END);
if (startIndex === -1 || endIndex === -1) throw new Error(`TECH-STRIP markers not found in ${file}`);

const next = html.slice(0, startIndex) + `${START}\n${section}\n${END}` + html.slice(endIndex + END.length);
await writeFile(file, next);
console.log(`Wrote ${icons.length} technology chips into ${file}`);
